import express from "express";
import bodyParser from "body-parser";

const app = express();
const port = process.env.PORT || 3000;

// Serve static files and parse request bodies
app.use(express.static("public"));
app.use(bodyParser.urlencoded({ extended: true }));

// Homepage route
app.get("/", (req, res) => {
  res.render("index.ejs", {
    heading: "<h1>Welcome to Date Suggestions! 💕</h1>",
    result: "",
  });
});

// POST request handler
app.post("/generate", (req, res) => {
  const category = req.body.category;
  const randomIdea = generateRandomIdea(category, categories);

  res.render("index.ejs", {
    heading: "<h1>Your Date Suggestion 💕</h1>",
    result: `<p>${randomIdea}</p>`,
  });
});

app.listen(port, () => {
  console.log(`Listening on port ${port}`);
});

// Helper function to generate a random idea
function generateRandomIdea(category, categories) {
  if (category === "Wildcard") {
    const randomCategory =
      Object.keys(categories)[
        Math.floor(Math.random() * Object.keys(categories).length)
      ];
    const randomActivity =
      categories[randomCategory][
        Math.floor(Math.random() * categories[randomCategory].length)
      ];
    return `Wildcard chose: ${randomCategory} - ${randomActivity}`;
  } else {
    const activities = categories[category];
    const randomActivity =
      activities[Math.floor(Math.random() * activities.length)];
    return `${category} - ${randomActivity}`;
  }
}

// Define categories and their activities
const categories = {
  Cozy: [
    "Doom scroll through brain-rot reels for an hour",
    "Watch a movie marathon",
    "Have a board game night",
    "Binge-watch childhood cartoons like Tom & Jerry",
    "Order biryani or maqluba and eat picnic-style on the living room floor",
    "Play ludo or carrom for a nostalgic evening",
    "Have a chai-making contest",
    "Set up a cozy tent in the living room",
    "Go through old family photo albums together",
    "Watch a Bollywood or South Indian classic movie",
    "Watch an Arabic make-you-weep movie",
    "Watch an Arabic classic rom-com",
    "Take a lazy day and scroll TikTok together",
    "Try aromatherapy or a relaxing massage at home",
    "Do a themed snack night with South Asian street food",
    "Paint pottery or sketch designs together",
    "Learn Arabic and Urdu phrases and laugh at accents",
    "Explore a new grocery store with cultural ingredients",
    "Watch vlogs of your dream travel destinations",
    "Write short poems for each other and read them aloud",
    "Have a picnic on the floor with sandwiches and juice",
    "Host a movie night with classic rom-coms",
    "Share your favorite childhood bedtime stories",
    "Plan your next big vacation in detail",
    "Watch an inspiring documentary about food or culture",
    "Plant herbs or small flowers in pots together",
    "Create a Spotify playlist and dance along",
    "Spend the day reorganizing your living space",
    "Play charades using cultural movie titles",
    "Do a meditation or yoga session for couples",
    "Doom scroll through brain-rot reels for an hour",
    "Make a scrapbook to track your adventures",
    "Watch nostalgic cartoons like Captain Majid",
    "Light incense or bakhoor for a calming mood",
    "Plan an at-home brunch with shakshuka",
    "Play a blindfold food tasting game with snacks",
    "Set up a home karaoke night and sing together",
    "Write down your favorite qualities about each other",
    "Explore cuisines by trying a new dish every week",
    "Bake something sweet like basbousa or halwa",
    "Have a spa night with bath bombs and music",
    "Watch a comedy show or stand-up special together",
    "Spend time journaling your favorite things about each other",
    "Solve crossword puzzles or Sudoku together",
    "Watch food vlogs to discover must-try dishes",
    "Have a “self-care Sunday” with face masks and tea",
    "Spend time stargazing from your balcony or backyard",
    "Plan a surprise takeout night featuring a new cuisine",
    "Go online shopping and add something to your wish-list",
    "Write and send postcards to each other",
    "Have a chai and conversation night about books",
    "Organize a closet cleanout together and laugh at old outfits",
    "Spend time decorating your home with cultural items",
    "Host a themed snack night with mezze or samosas",
    "Try folding paper into origami flowers or animals",
    "Celebrate “lazy day” with pajamas and instant noodles",
    "Do a neighborhood walk and find hidden gems nearby",
    "Create a photo wall with your favorite memories",
    "Write down your life goals and create a vision board",
    "Have a video game marathon with multiplayer games",
    "Try decorating cupcakes or cookies with cultural patterns",
    "Plan an evening learning a cultural dance together",
    "Read cultural folktales and compare versions from both regions",
    "Watch each other’s favorite childhood TV shows or cartoons",
    "Spend a day baking bread or making desserts like kunafa",
    "Go for a casual walk or drive and grab takeout from a roadside vendor",
    "Plan your next grocery run together and experiment with cooking tools",
    "Create a fun playlist featuring your favorite cultural songs",
    "Decorate your living space for a cozy theme night",
    "Order or make jalebi or baklava and share it with chai",
    "Recreate your dream date at home with candles and takeout",
    "Decorate mugs with your names or cultural symbols together",
    "Doom scroll through brain-rot reels for an hour",
    "Watch old cultural cooking shows and try recipes together",
    "Plan a weekend exploring classic spots in your city",
    "Have a photo shoot night with cultural outfits or accessories",
    "Reorganize your space while playing brain-rot songs in the background",
    "Learn a traditional craft like henna designs or embroidery together",
    "Find nostalgic snacks from childhood and enjoy them together",
    "Create custom playlists for specific moods and listen together",
    "Plan an “around the world” theme night with cultural dishes",
    "Light candles and enjoy a quiet evening chatting about life."
  ],
  
  Outdoorsy: [
    "Hike up Mont Royal and enjoy the view from the Kondiaronk Belvedere",
    "Walk along the Old Port and grab ice cream at a local creamery",
    "Take a day trip to Quebec City and explore Old Quebec",
    "Visit Parc Jean-Drapeau and rent a paddleboat",
    "Explore the Lachine Canal by bike or foot",
    "Attend a food festival or event at Atwater Market",
    "Drive to Ottawa and visit the Canadian Museum of History",
    "Plan a beach day at Plage Saint-Zotique",
    "Go apple picking at a nearby orchard during fall",
    "Take a scenic drive to Mont-Tremblant and hike its trails",
    "Go snowshoeing or sledding in Parc Maisonneuve during winter",
    "Spend the day kayaking or canoeing at Parc de la Rivière-des-Mille-Îles",
    "Take a ferry to Îles-de-Boucherville National Park for hiking and wildlife watching",
    "Visit the lavender fields at Bleu Lavande in Magog during summer",
    "Plan a picnic at Parc Angrignon and explore its trails",
    "Go ziplining at Arbraska adventure park in Rigaud",
    "Take a food tour of Little Italy and Jean-Talon Market",
    "Go fishing or birdwatching in Parc Nature de l’Île-de-la-Visitation",
    "Drive to Ontario and visit the nearest Popeyes for a treat!",
    "Plan a camping trip to Mont Orford National Park",
    "Explore the historic sites and cafes of Old Montreal",
    "Visit Saint-Sauveur for skiing or water park fun, depending on the season",
    "Take a guided tour of Montreal’s underground city in winter",
    "Spend the day at La Ronde amusement park",
    "Go whale watching in Tadoussac on a weekend trip",
    "Take a scenic train ride on the Orford Express",
    "Plan a trip to Toronto and explore Kensington Market and CN Tower",
    "Walk through the Montreal Botanical Garden and its themed gardens",
    "Visit Oka National Park for hiking or beach relaxation",
    "Rent scooters and explore the Plateau neighborhood",
    "Go ice skating at Beaver Lake on Mont Royal during winter",
    "Attend an outdoor movie screening at Cinéma sous les étoiles",
    "Explore street art and murals in the Plateau and Mile End neighborhoods",
    "Take a sunset cruise on the St. Lawrence River",
    "Visit Parc Omega in Montebello for a wildlife safari experience",
    "Explore the caves at Saint-Elzéar on a weekend getaway",
    "Go mountain biking at Bromont Mountain Resort",
    "Walk across the illuminated Jacques-Cartier Bridge at night",
    "Try dog sledding in the Laurentians during winter",
    "Visit Brome-Missisquoi for a wine-tasting tour",
    "Go on a food truck crawl at a summer event downtown",
    "Attend the International Fireworks Festival at the Old Port",
    "Take a guided boat tour to explore Montreal’s waterways",
    "Spend the day at Tremblant Village for shopping and outdoor activities",
    "Visit the Montmorency Falls near Quebec City",
    "Explore Griffintown and visit local cafes and restaurants",
    "Play mini-golf at an outdoor course like Putting Edge Laval",
    "Walk along the Sainte-Anne-de-Bellevue boardwalk",
    "Visit an outdoor market like Marché Atwater or Jean-Talon Market",
    "Plan a ski trip to Mont Sutton in the Eastern Townships",
    "Take a ferry to Île Sainte-Hélène and explore Parc Jean-Drapeau",
    "Attend an outdoor concert at Place des Festivals",
    "Visit an outdoor shisha café in Montreal",
    "Go stargazing in Mont-Mégantic International Dark Sky Reserve",
    "Explore the historic canals and locks at Sainte-Anne-de-Bellevue",
    "Attend a Cirque du Soleil outdoor performance in Montreal",
    "Go horseback riding in Montérégie",
    "Spend a day at Saint-Hubert or Boisbriand outlet malls",
    "Visit the Canadian Railway Museum in Saint-Constant",
    "Try outdoor yoga or fitness classes in Jeanne-Mance Park",
    "Plan a road trip along the Eastern Townships Wine Route",
    "Spend an afternoon exploring Pointe-Claire Village",
    "Take a helicopter tour of Montreal for a unique perspective",
    "Go berry picking at Quinn Farm in Notre-Dame-de-l’Île-Perrot",
    "Explore Sainte-Agathe-des-Monts and its charming lakes",
    "Attend the Montreal Jazz Festival’s outdoor events",
    "Visit the Biodome and nearby parks for a nature-filled day",
    "Go windsurfing or paddleboarding at Oka Beach",
    "Explore Île aux Tourtes for hiking and nature watching",
    "Visit the Tulip Festival in Ottawa during spring",
    "Take a ghost tour in Old Montreal for a spooky adventure",
    "Visit Sainte-Anne Canyon near Quebec City for stunning views",
    "Go karting at Action 500 in Laval or Montreal",
    "Spend a day hiking or relaxing by Lake Memphremagog",
    "Walk through Quartier des Spectacles during a festival",
    "Take a hot air balloon ride in Saint-Jean-sur-Richelieu",
    "Visit Parc des Rapides and spot herons along the St. Lawrence",
    "Plan a road trip to explore Charlevoix’s scenic landscapes",
    "Attend a local sugar shack experience during maple syrup season",
    "Spend a winter day tubing at Mont Avila",
    "Go horseback riding in Mont Rigaud’s trails",
    "Visit Alouette Beach for a relaxing summer day",
    "Explore Vieux-Limoilou in Quebec City for its cafes and charm",
    "Go to Parc du Mont Bellevue in Sherbrooke for biking or hiking",
    "Attend Igloofest, Montreal’s outdoor electronic music festival in winter",
    "Explore the Mont-Royal Cemetery for a peaceful walk",
    "Visit the Écomuseum Zoo in Sainte-Anne-de-Bellevue",
    "Take a canoe or kayak trip through the Yamaska River",
    "Walk along the Chambly Canal for a tranquil day outdoors",
    "Plan a waterfall-hopping trip to Quebec’s best falls",
    "Take a river cruise to explore Montreal’s skyline from the water",
    "Drive to Kingston for a scenic Thousand Islands boat tour."
  ],
  
  Foodie: [
    "Explore a new restaurant in Old Montreal",
    "Visit Jean-Talon Market and try exotic fruits",
    "Cook homemade butter chicken with naan",
    "Try Montreal’s famous smoked meat sandwiches at Schwartz’s Deli",
    "Visit a food truck festival and sample street food",
    "Plan a sushi night at home with fresh ingredients from a Japanese market",
    "Take a cooking class together at Ateliers et Saveurs",
    "Explore poutine variations at La Banquise",
    "Try decorating cupcakes with cultural motifs",
    "Bake bread together and enjoy the fresh aroma",
    "Discover Middle Eastern flavors at KazaMaza",
    "Recreate your favorite cultural street food dishes at home",
    "Bake homemade croissants together",
    "Try Ethiopian food at Mesob Restaurant",
    "Cook a vegetarian day with cultural recipes",
    "Make a charcuterie board featuring Quebec cheeses",
    "Recreate street snacks like samosas or falafel",
    "Visit Little Italy and enjoy authentic pizza at Bottega",
    "Have brunch at Arthurs Nosh Bar on Notre-Dame Street",
    "Cook a fancy steak dinner with wine pairings at home",
    "Try authentic ramen at Yokato Yokabai",
    "Explore Chinatown and grab bubble tea and dim sum",
    "Bake a South Asian dessert like gulab jamun or jalebi",
    "Spend a day making traditional sweets for a cultural festival",
    "Discover Lebanese mezze at Omnivore or Boustan",
    "Make homemade Montreal-style bagels from scratch",
    "Visit a bakery and try freshly baked pain au chocolat",
    "Explore Turkish cuisine with dishes like lahmacun or pide",
    "Host a DIY taco night with a variety of fillings",
    "Sample different kinds of croquetas at a Spanish tapas bar",
    "Find the best cannoli in town in Little Italy",
    "Try Filipino dishes like adobo or halo-halo at Kamayan Counter",
    "Make fresh pasta from scratch and pair it with a creamy sauce",
    "Recreate your favorite cultural breakfast dishes at home",
    "Experiment with making your favorite childhood snacks at home",
    "Explore Korean barbecue at Hwang Kum or Matjip BBQ",
    "Visit a chocolatier like Juliette & Chocolat and indulge in fondue",
    "Host a wine and cheese tasting night at home",
    "Sample fresh oysters at Maison Publique",
    "Cook homemade shakshuka for a cozy brunch at home",
    "Enjoy authentic Portuguese pastries like pastéis de nata from a local bakery",
    "Try a tasting menu at Tuck Shop or Joe Beef",
    "Have a picnic at Parc Laurier with charcuterie and baguettes",
    "Make dumplings or momos from scratch together",
    "Explore vegan cuisine at LOV or Aux Vivres",
    "Host a spice-tasting night and cook dishes from different countries",
    "Try Caribbean flavors like jerk chicken at Mango Bay",
    "Visit a Persian restaurant for kebabs and saffron rice",
    "Make homemade bubble tea using tapioca pearls",
    "Discover Peruvian ceviche at Tiradito or Chicha",
    "Plan a pizza tasting night with slices from different pizzerias",
    "Explore Syrian cuisine at Alep Restaurant",
    "Cook a big pot of pho or tom yum soup at home",
    "Visit La Fromagerie Hamel and sample artisan cheeses",
    "Host a Middle Eastern night with shawarma and baklava",
    "Enjoy churros with hot chocolate at a Latin American café",
    "Try gourmet hot dogs at Dirty Dogs Montreal",
    "Play a cooking roulette game with random ingredients",
    "Explore Haitian cuisine at La Belle Tonki or Agrikol",
    "Cook a Moroccan tagine with preserved lemons and olives",
    "Visit an Indian buffet for unlimited naan and curries",
    "Make crepes at home and pair them with Nutella and fruit",
    "Sample desserts at Pâtisserie Rhubarbe",
    "Visit Mile End for authentic falafel or shawarma wraps",
    "Try dishes from a Québécois cabane à sucre during maple season",
    "Make homemade sushi rolls with your favorite fillings",
    "Discover French bistro cuisine at L’Express",
    "Plan a ramen or udon tasting at local noodle shops",
    "Explore vegan desserts at Sophie Sucrée",
    "Try authentic Mexican tacos at Escondite",
    "Host a blind taste test of chocolates or coffee brands",
    "Enjoy lobster rolls at Lucille’s Oyster Dive",
    "Cook a South Asian biryani together",
    "Visit a café and enjoy artisanal matcha lattes",
    "Bake your favorite childhood cookies or treats",
    "Try Thai cuisine at Pamika or Thaï Sep",
    "Enjoy Montreal’s classic bagel with smoked salmon from St-Viateur or Fairmount",
    "Cook authentic Italian risotto or osso buco",
    "Visit a patisserie and sample éclairs or mille-feuilles",
    "Explore craft beer pairings with pub food at Dieu du Ciel!",
    "Make homemade ice cream or gelato from scratch",
    "Sample dim sum delicacies at La Maison Kam Fung",
    "Visit a farm-to-table restaurant like Candide",
    "Try jerk chicken poutine at a fusion eatery",
    "Explore South Asian street food like chaat or pani puri",
    "Have a waffle and fried chicken brunch at L’Avenue",
    "Discover Nordic-inspired dishes at Restaurant Helena",
    "Host a hot pot night at home with friends",
    "Explore Georgian cuisine and try khachapuri at a local spot",
    "Cook a Spanish paella with fresh seafood",
    "Plan a tea-tasting session with artisanal teas",
    "Visit a Syrian bakery for manakish or kaak",
    "Make your own ramen broth from scratch and experiment with toppings",
    "Sample gelato at a local spot like Havre-aux-Glaces",
    "Enjoy a hearty steak-frites dinner at a classic bistro",
    "Try Sri Lankan kottu roti or hoppers at a new spot",
    "Cook Middle Eastern grilled kofta with yogurt sauce",
    "Explore Brazilian cuisine with feijoada or pão de queijo",
    "Visit a butcher and cook dry-aged beef steaks at home",
    "Sample pides or kebabs at a Turkish eatery",
    "Try authentic French onion soup at a local bistro",
    "Bake a cake or dessert from a family recipe",
    "Have a bubble waffle or taiyaki dessert adventure downtown",
    "Host a Middle Eastern spice exploration night with za'atar and sumac",
    "Try Montreal’s famous crème brûlée at a local café"
  ],  
};
